describe('About 페이지로 이동', () => {
  beforeEach(() => {
    // alias the $btn.text() as 'text'
    cy.visit('/')
    cy.get('header .nav-link.active')
      .contains('Search')
    cy.wait(2000)
  })
  it('About 페이지로 이동', () => {
    cy.get('header .nav-link')
      .contains('About')
      .click()
    cy.url().should('include', '/about')
    cy.wait(1000)
    cy.get('header .nav-link.active')
      .contains('About')
    cy.get('.name')
      .contains('SEUNG JIN')
  })
  it('About 페이지에서 Movie 페이지로 이동', () => {
    cy.get('header .nav-link')
      .contains('About')
      .click()
    cy.url().should('include', '/about')
    cy.wait(1000)
    cy.get('header .nav-link.active')
      .contains('About')
    cy.get('header .nav-link')
      .contains('Movie')
      .click()
    cy.url().should('include', '/movie')
  })
  it('아이콘을 이용해서 About 페이지로 이동', () => {
    cy.get('header .user')
      .click()
    cy.url().should('include', '/about')
    cy.wait(1000)
    cy.get('header .nav-link.active')
      .contains('About')
    cy.get('.name')
      .contains('SEUNG JIN')
  })
})

